### PR TITLE
Switch to using go modules

### PR DESCRIPTION
**Pull request by ianmcorvidae**
This is basically a janitorial task, but anyway. Built the docker image from this and it worked (once I fixed the older config I had lying around).

### CODE REVIEW

**Review by slr71 — COMMENTED** [review]
It's possible to clean this up a little more when you switch to Go modules by making a couple of small changes to the Dockerfle. The changes that are required are to switch to a more recent version of Go and to switch to the directory containing the source code before building the project. Here's the diff:

```
diff --git a/Dockerfile b/Dockerfile
index 91069f8..c09b9ef 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM golang:1.11-alpine
+FROM golang:1.15-alpine

 RUN apk add --no-cache git
 RUN go get -u github.com/jstemmer/go-junit-report
@@ -13,7 +13,8 @@ LABEL org.cyverse.descriptive-version="$descriptive_version"

 COPY . /go/src/github.com/cyverse-de/infosquito2
 ENV CGO_ENABLED=0
-RUN go install -v -ldflags "-X main.appver=$version -X main.gitref=$git_commit" github.com/cyverse-de/infosquito2
+RUN cd /go/src/github.com/cyverse-de/infosquito2 && \
+    go install -v -ldflags "-X main.appver=$version -X main.gitref=$git_commit" .

 EXPOSE 60000
 LABEL org.label-schema.vcs-ref="$git_commit"
```

Once you've done that, the following changes can be made.

- `Gopkg.lock` can be removed.
- `Gopkg.toml` can be removed.
- The entire `vendor` directory can be removed and added to `.gitignore`.

**Comment by ianmcorvidae** [comment]
Oh, I should have removed the Gopkg files already and forgot to. I had kept the vendor directory deliberately because it seemed safer, but if we've been doing it the other way then that's better. I'll make those changes, thanks for the comment! To be honest I'd sorta forgotten I did this PR :sweat_smile: so it's good you did!

**Review by slr71 — APPROVED** [review]
LGTM! :shipit:

**Comment by slr71** [comment]
I'd actually forgotten about this too. I was just browsing through open PRs and thought this looked like something I could review quickly. 😄

**Comment by ianmcorvidae** [comment]
Cool, thanks for the review!

**Pull request merged**
